# Generated by Django 2.1.7 on 2019-03-06 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('categoria', models.SmallIntegerField(choices=[(1, 'Empréstimo'), (2, 'Pagamento de empréstimo'), (3, 'Alimentação'), (4, 'Diversão')])),
                ('descricao', models.CharField(max_length=300)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
